import fs from 'node:fs';
import path from 'node:path';
import matter from 'gray-matter';
import { visit } from 'unist-util-visit';
import type { Root } from 'mdast';
import { CONTENT_DIR, resolveAsset } from './publishing';
import catalogue from './tool-contract/catalogue.json';
import { validateState } from './tool-contract/schema.js';
import { validateCatalogue, selectView, validateControls, embedFragment } from './tool-contract/definition.js';
import { fullToolURL } from './tool-contract/codec.js';
import { isLegacyExample, validateLegacyExample, legacyExampleURLs } from './tool-contract/legacy.js';

export const TOOLS_ORIGIN = 'https://tools.matthewgarner.me';
// This local, versioned export is generated by Tools. No tool engines enter the website.
export const toolCatalogue = validateCatalogue(catalogue);
export type ToolExample = {
  tool: string; version: number; view: string; title: string; summary: string;
  image: string; alt: string; controls: string[]; state?: unknown;
  params?: Record<string, unknown>; seed?: number;
};
const text = (value: unknown, label: string): string => {
  if (typeof value !== 'string' || !value.trim()) throw new Error(`Tool example needs ${label}.`);
  return value.trim();
};
const object = (value: unknown): value is Record<string, unknown> => !!value && typeof value === 'object' && !Array.isArray(value);
function keys(value: Record<string, unknown>, allowed: string[]) {
  for (const key of Object.keys(value)) if (!allowed.includes(key)) throw new Error(`Unknown tool option: ${key}`);
}
function definitionFor(value: Record<string, unknown> | ToolExample, registry = toolCatalogue) {
  const definition = registry.tools.find((tool: { id: string; version: number }) => tool.id === value.tool && tool.version === value.version);
  if (!definition) throw new Error('Unsupported tool, version or view. Sync the released Tools catalogue before using a new tool.');
  return definition;
}
export function validateExample(value: unknown, registry = toolCatalogue): ToolExample {
  if (!object(value)) throw new Error('Tool example must be an object.');
  if (typeof value.tool !== 'string' || typeof value.view !== 'string' || !Number.isSafeInteger(value.version)) throw new Error('Unsupported tool, version or view.');
  for (const field of ['title', 'summary', 'image', 'alt']) text(value[field], field);
  if (!/\.(?:svg|png|jpe?g|webp|avif)$/i.test(String(value.image)) || /^(?:[a-z]+:|\/\/)/i.test(String(value.image))) {
    throw new Error('Tool fallback must be a local image.');
  }
  if (isLegacyExample(value)) {
    keys(value, ['tool', 'version', 'view', 'title', 'summary', 'image', 'alt', 'params', 'seed', 'controls']);
    validateLegacyExample(value);
  } else {
    const definition = definitionFor(value, registry);
    const selection = selectView(definition, value.view, value.controls);
    keys(value, ['tool', 'version', 'view', 'title', 'summary', 'image', 'alt', 'state', 'controls']);
    if (!Object.hasOwn(value, 'state')) throw new Error('Tool example needs state.');
    if (!Array.isArray(value.controls)) throw new Error('Tool example needs an explicit controls list.');
    const state = validateState(definition, value.state);
    validateControls(definition, state, selection.controls);
    // Fail authoring on invalid or oversized handoffs, before generating any HTML.
    fullToolURL(definition, state);
  }
  return value as ToolExample;
}
export function readExample(id: string, root = CONTENT_DIR): ToolExample {
  if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(id)) throw new Error(`Invalid tool example name: ${id}`);
  const directory = path.join(root, 'tool-examples');
  const file = path.join(directory, `${id}.json`);
  // Content publishing excludes symlinks; example loading must honour that boundary too.
  if (fs.lstatSync(directory).isSymbolicLink() || fs.lstatSync(file).isSymbolicLink()) throw new Error('Tool examples cannot be symlinks.');
  const stat = fs.statSync(file);
  if (!stat.isFile() || stat.size > 524288) throw new Error('Tool example must be a JSON file smaller than 512 KiB.');
  return validateExample(JSON.parse(fs.readFileSync(file, 'utf8')));
}
const escape = (value: string) => value.replace(/[&<>"']/g, ch => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[ch]!);
function validateOrigin(origin: string) {
  const url = new URL(origin);
  if (url.origin !== origin || !(origin === TOOLS_ORIGIN || (url.protocol === 'http:' && ['127.0.0.1', 'localhost'].includes(url.hostname)))) {
    throw new Error('Tool embed origin must be Tools Lab or a local preview server.');
  }
}
export function exampleURLs(example: ToolExample, origin = TOOLS_ORIGIN, registry = toolCatalogue) {
  validateOrigin(origin);
  if (isLegacyExample(example)) {
    const { embedUrl, fullToolUrl } = legacyExampleURLs(example, origin);
    return { src: embedUrl, full: fullToolUrl };
  }
  const definition = definitionFor(example, registry);
  const src = origin + definition.route + embedFragment({ state: example.state, view: example.view, controls: example.controls });
  const full = new URL(fullToolURL(definition, example.state));
  // Local paired previews follow local Tools routes; Energy keeps its own origin.
  if (origin !== TOOLS_ORIGIN && full.origin === TOOLS_ORIGIN) return { src, full: origin + full.pathname + full.hash };
  return { src, full: full.href };
}

/** Expand authored examples into accessible figures. JS is an optional enhancement. */
export function articleTools({ root = CONTENT_DIR, origin = TOOLS_ORIGIN } = {}) {
  validateOrigin(origin);
  return (tree: Root, file: { path?: string }) => {
    visit(tree, 'code', (node, index, parent) => {
      if (node.lang !== 'tool' || !parent || index === undefined) return;
      const options = matter(`---\n${node.value}\n---`).data;
      keys(options, ['example', 'caption', 'mode']);
      const id = text(options.example, 'example');
      const example = readExample(id, root);
      const caption = options.caption === undefined ? example.summary : text(options.caption, 'caption');
      const mode = options.mode ?? 'interactive';
      if (!['interactive', 'figure'].includes(mode)) throw new Error('Tool mode must be interactive or figure.');
      const from = file.path ? path.relative(root, file.path).split(path.sep).join('/') : 'index.md';
      const image = resolveAsset(example.image, from, root);
      const { src, full } = exampleURLs(example, origin);
      parent.children[index] = { type: 'html', value:
        `<figure class="tool-demo"${mode === 'interactive' ? ` data-tool-src="${escape(src)}" data-tool-title="${escape(example.title)}"` : ''}>` +
        `<div class="tool-demo-stage"><img class="tool-demo-poster" src="${escape(image)}" alt="${escape(example.alt)}" loading="lazy" /></div>` +
        `<figcaption>${escape(caption)}</figcaption>` +
        `<div class="tool-demo-actions">${mode === 'interactive' ? '<button type="button" data-tool-start hidden>Explore this example</button>' : ''}` +
        `<a href="${escape(full)}" target="_blank" rel="noopener">Open full tool <span aria-hidden="true">↗</span></a></div>` +
        '<p class="tool-demo-status" role="status" aria-live="polite"></p></figure>' };
    });
  };
}
